import Nav from "@/components/shared/Navbar"
import '../globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Nav></Nav>
      <body>{children}</body>
    </html>
  )
}
